### PR TITLE
Adds social buttons, hash navigation

### PR DESCRIPTION
**Pull request by csessig86**
Social buttons added for mobile users. Hash navigation added to allow
mobile users to share individual pages. Also changed the topic 'public safety' back into 'criminal law'

### CODE REVIEW

**Comment by afrerich** [comment]
I pushed this out, although I'm not quite sure if it's working or not. It
seems like I get the social buttons only every now and then, and only on
the category pages.

On Tue, Mar 5, 2013 at 6:49 PM, Chris Essig notifications@github.comwrote:

> Social buttons added for mobile users. Hash navigation added to allow
> mobile users to share individual pages. Also changed the topic 'public
> 
> ## safety' back into 'criminal law'
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/csessig86/billtracker master
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/Fusionfarm/billtracker/pull/9
> Commit Summary
> - Add social buttons, hash navigation
> 
> File Changes
> - _M_ public/ia_bill_watch/css/styles.csshttps://github.com/Fusionfarm/billtracker/pull/9/files#diff-0(10)
> - _A_ public/ia_bill_watch/icons/criminal-law.pnghttps://github.com/Fusionfarm/billtracker/pull/9/files#diff-1(0)
> - _A_ public/ia_bill_watch/icons/criminal-law.svghttps://github.com/Fusionfarm/billtracker/pull/9/files#diff-2(0)
> - _M_ public/ia_bill_watch/index.htmlhttps://github.com/Fusionfarm/billtracker/pull/9/files#diff-3(85)
> - _A_ public/ia_bill_watch/js/jquery.ba-hashchange.min.jshttps://github.com/Fusionfarm/billtracker/pull/9/files#diff-4(9)
> - _M_ public/ia_bill_watch/js/script.jshttps://github.com/Fusionfarm/billtracker/pull/9/files#diff-5(255)
> - _R_ public/ia_bill_watch/js/script_no_hash.jshttps://github.com/Fusionfarm/billtracker/pull/9/files#diff-6(2010)
> 
> Patch Links:
> - https://github.com/Fusionfarm/billtracker/pull/9.patch
> - https://github.com/Fusionfarm/billtracker/pull/9.diff

## 

http://www.aaronfrerichs.com
email: afrerich@gmail.com
twitter: @aaron_frerichs https://twitter.com/aaron_frerichs
google plus: http://gplus.to/aaronfrerichs

**Comment by csessig86** [comment]
What type of mobile phone are you using? The buttons are working on my iPhone.

**Comment by afrerich** [comment]
Ah, never mind. I missed the "for mobile users" part of the comment. I checked it on my android phone and the buttons are consistently there.

**Comment by csessig86** [comment]
Got it. The way it works is the buttons will only show up if the window width is below 600px. So that would be all of our mobile users. But I may lower that because when the scrollbar is attached to the iframe, the buttons start to show up because the window is now under 600px (the scrollbar takes up a few pixels). So I'm going to drop that down to 550px and submit yet another pull request. I'll test it after that. Once that's all done, we should be able to launch this. Finally.

**Pull request merged**
